# Robot. 
map_frame_id:                               map 
robot_base_frame_id:                        cam_tracking_link 
robot_pose_with_covariance_topic:           /camera_footprint_pose
robot_pose_cache_size:                      200
#point_cloud_topic:                          /cam_depth/depth/color/points #/filtered_points #/camera/depth/color/points 
track_point_frame_id:                       map #cam_tracking_link  #this defines how the elevation map moves 

track_point_x:                              -0.05 
track_point_y:                              -0.15
track_point_z:                              0.0
min_update_rate:                            2.0
time_tolerance:                             1.0
time_offset_for_point_cloud:                0.0


#note that this is the height relative to the camera's position at each momentmap
#sensor_processor/ignore_points_above:       -0.34 #height of the plane + 10cm TODO: change this so to set this as a variable
#sensor_processor/ignore_points_below:       -0.44 #height of the plane 
robot_motion_map_update/covariance_scale:   0.01 #no documentation on this

# Map
#x and y are "flipped" 
length_in_x:                                1.0  #1.5
length_in_y:                                3.0 #0.5
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.005 #what is the minimum resolution?? 
 #maybe changing this will produce a more reliable map in the x-y direction
#min_variance:                               0.0001
#max_variance:                               0.05 

mahalanobis_distance_threshold:             2.5   #how many standard deviations away the new data has to be for it to be rejected
#comment this out too
#multi_height_noise:                         0.001
max_horizontal_variance:                    0.01
surface_normal_positive_axis:               z
fused_map_publishing_rate:                  0.5
enable_visibility_cleanup:                  false
visibility_cleanup_rate:                    1.0
scanning_duration:                          1.0

# Init submap #currently not used
initialize_elevation_map:                   false
initialization_method:                      0
length_in_x_init_submap:                    1.0
length_in_y_init_submap:                    1.0
margin_init_submap:                         0.3
init_submap_height_offset:                  0.01
target_frame_init_submap:                   cam_tracking_link
